import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import RouteProtector from "@/components/admin/RouteProtector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import Sidebar from "@/components/admin/Sidebar";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Celebd Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <RouteProtector>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <Sidebar>{children}</Sidebar>
            </ThemeProvider>
          </RouteProtector>
        </body>
      </html>
    </ClerkProvider>
  );
}
