import Tops from "@/assets/images/celebd-categories-image-top.jpg";
import Hoodies from "@/assets/images/celebd-categories-image-hoodie-2.jpg";
import SweatShirts from "@/assets/images/celebd-categories-image-sweatshirts.jpg";
import CropTop from "@/assets/images/celebd-categories-image-croped-top.jpg";
import Shorts from "@/assets/images/celebd-categories-image-shorts.jpg";
import Caps from "@/assets/images/celebd-categories-image-cap.jpg";

export const Collections = [
  {
    id: 1,
    name: "HOODIES",
    slug: "hoodies",
    image: Hoodies,
  },
  {
    id: 2,
    name: "CROP-TOP",
    slug: "CropTop",
    image: CropTop,
  },
  {
    id: 3,
    name: "SHORTS",
    slug: "shorts",
    image: Shorts,
  },
  {
    id: 4,
    name: "TOPS",
    slug: "tops",
    image: Tops,
  },
  {
    id: 5,
    name: "SWEATSHIRTS",
    slug: "sweatshirts",
    image: SweatShirts,
  },
  {
    id: 6,
    name: "CAPS",
    slug: "caps",
    image: Caps,
  },
];

export const Products = [
  {
    id: 1,
    productId: "PROD001",
    title: "Accolade Crew Neck Pullover",
    slug: "accolade-crew-neck-pullover-seashell-blue",
    brand: "Alo Yoga",
    description:
      "Comfortable and stylish pullover, perfect for workouts and casual wear.",
    category: "Apparel",
    tags: ["pullover", "crew neck", "blue", "casual"],
    price: 11600,
    discountPrice: 11600,
    currency: "INR",
    inStock: true,
    quantity: 25,
    variants: {
      colors: ["Seashell Blue"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_05442_b1_s1_a1_m233_1600x1600.jpg?v=1749464233",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_05442_b1_s1_a4_m233_2000x2000.jpg?v=1749835805",
    ],
    videoUrl: "",
    rating: {
      average: 4.5,
      count: 38,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "400g",
      material: "Cotton blend",
      fit: "Regular fit",
    },
    warranty: "No warranty",
  },
  {
    id: 2,
    productId: "PROD002",
    title: "Match Point Short",
    slug: "match-point-short-seashell-blue",
    brand: "Alo Yoga",
    description:
      "Lightweight shorts designed for maximum comfort and mobility.",
    category: "Apparel",
    tags: ["shorts", "activewear", "blue"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 40,
    variants: {
      colors: ["Seashell Blue"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W6334R_05442_b2_s1_a1_m18_1600x1600.jpg?v=1749543226",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W6334R_05442_b1_s1_ai_m91_2000x2000.jpg?v=1749640572",
    ],
    videoUrl: "",
    rating: {
      average: 4.4,
      count: 25,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "250g",
      material: "Polyester",
      fit: "Relaxed fit",
    },
    warranty: "No warranty",
  },
  {
    id: 3,
    productId: "PROD003",
    title: "Accolade Crew Neck Pullover",
    slug: "accolade-crew-neck-pullover-pink-quartz",
    brand: "Alo Yoga",
    description:
      "Soft pullover in elegant pink quartz, ideal for relaxed or sporty looks.",
    category: "Apparel",
    tags: ["pullover", "pink", "crew neck"],
    price: 11600,
    discountPrice: 11600,
    currency: "INR",
    inStock: true,
    quantity: 20,
    variants: {
      colors: ["Pink Quartz"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_06027_b2_s1_a5_m186_8ac61799-6a2d-446c-ae29-3236b371fbeb_1600x1600.jpg?v=1744848658",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_06027_b1_s1_a4_m231_2000x2000.jpg?v=1749146657",
    ],
    videoUrl: "",
    rating: {
      average: 4.6,
      count: 30,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "400g",
      material: "Cotton blend",
      fit: "Regular fit",
    },
    warranty: "No warranty",
  },
  {
    id: 4,
    productId: "PROD004",
    title: "Accolade Sweatpant",
    slug: "accolade-sweatpant-pink-quartz",
    brand: "Alo Yoga",
    description:
      "Cozy sweatpants perfect for lounging or light activity. Cozy sweatpants perfect for lounging or light activity.Cozy sweatpants perfect for lounging or light activity.",
    category: "Apparel",
    tags: ["sweatpants", "pink", "casual"],
    price: 11600,
    discountPrice: 11600,
    currency: "INR",
    inStock: true,
    quantity: 15,
    variants: {
      colors: ["Pink Quartz"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U5013RG_06027_b2_s1_a1_m229_1600x1600.jpg?v=1747165878",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U5013RG_06027_b1_s1_a1_m231_2000x2000.jpg?v=1747165878",
    ],
    videoUrl: "",
    rating: {
      average: 4.5,
      count: 18,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "500g",
      material: "Cotton blend",
      fit: "Relaxed fit",
    },
    warranty: "No warranty",
  },
  {
    id: 5,
    productId: "PROD005",
    title: "Cropped 1/4 Zip Alumni Pullover",
    slug: "cropped-1-4-zip-alumni-pullover-spearmint",
    brand: "Alo Yoga",
    description:
      "Trendy cropped pullover with a 1/4 zip for style and ventilation.",
    category: "Apparel",
    tags: ["pullover", "cropped", "green", "zip"],
    price: 10700,
    discountPrice: 10700,
    currency: "INR",
    inStock: true,
    quantity: 22,
    variants: {
      colors: ["Spearmint"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W3660R_06326_b2_s1_a1_m207_1600x1600.jpg?v=1747896940",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W3660R_06326_b1_s1_ai_m161_2000x2000.jpg?v=1748405979",
    ],
    videoUrl: "",
    rating: {
      average: 4.7,
      count: 20,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "350g",
      material: "Poly-cotton blend",
      fit: "Cropped fit",
    },
    warranty: "No warranty",
  },
  {
    id: 6,
    productId: "PROD006",
    title: "Airlift Super Sleek Contrast Bra",
    slug: "airlift-super-sleek-contrast-bra-candy-red-white",
    brand: "Alo Yoga",
    description: "Supportive and sleek sports bra with stylish color contrast.",
    category: "Apparel",
    tags: ["sports bra", "red", "white", "activewear"],
    price: 7100,
    discountPrice: 7100,
    currency: "INR",
    inStock: true,
    quantity: 30,
    variants: {
      colors: ["Candy Red/White"],
      sizes: ["XS", "S", "M", "L"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W9843R_06335_b2_s1_a1_m239_1600x1600.jpg?v=1746045737",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W9843R_06335_b1_s1_ai_m161_2000x2000.jpg?v=1746045737",
    ],
    videoUrl: "",
    rating: {
      average: 4.6,
      count: 28,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "200g",
      material: "Nylon-Spandex blend",
      fit: "Tight fit",
    },
    warranty: "No warranty",
  },
  {
    id: 7,
    productId: "PROD007",
    title: "Airlift High-Waist Super Sleek Contrast Capri",
    slug: "airlift-high-waist-super-sleek-contrast-capri-candy-red-white",
    brand: "Alo Yoga",
    description:
      "High-waist capri leggings with a sleek, sculpting design and bold contrast colors.",
    category: "Apparel",
    tags: ["leggings", "capri", "red", "white"],
    price: 11600,
    discountPrice: 11600,
    currency: "INR",
    inStock: true,
    quantity: 18,
    variants: {
      colors: ["Candy Red/White"],
      sizes: ["XS", "S", "M", "L"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W54232R_06335_b2_s1_a5_m239_1600x1600.jpg?v=1746045789",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W54232R_06335_b1_s1_ai_m161_24af9dfb-be3a-4e35-a095-dd7775aeaeeb_2000x2000.jpg?v=1746223663",
    ],
    videoUrl: "",
    rating: {
      average: 4.7,
      count: 23,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "300g",
      material: "Nylon-Spandex blend",
      fit: "Tight fit",
    },
    warranty: "No warranty",
  },
  {
    id: 8,
    productId: "PROD008",
    title: "Cropped Accolade Crewneck",
    slug: "cropped-accolade-crewneck-candy-red",
    brand: "Alo Yoga",
    description:
      "Cropped crewneck with a relaxed, casual vibe and soft fabric feel.",
    category: "Apparel",
    tags: ["pullover", "cropped", "red"],
    price: 10700,
    discountPrice: 10700,
    currency: "INR",
    inStock: true,
    quantity: 27,
    variants: {
      colors: ["Candy Red"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W3924RG_06281_b2_s1_a1_m18_1600x1600.jpg?v=1745839640",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W3924RG_06281_b1_s1_a4_m54_d15460dd-6a3e-4adf-bdde-bf4a0a6b42b6_2000x2000.jpg?v=1745866145",
    ],
    videoUrl: "",
    rating: {
      average: 4.5,
      count: 32,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "350g",
      material: "Cotton blend",
      fit: "Cropped fit",
    },
    warranty: "No warranty",
  },
  {
    id: 9,
    productId: "PROD009",
    title: "Airlift Advantage Racerback Bra",
    slug: "airlift-advantage-racerback-bra-pink-quartz",
    brand: "Alo Yoga",
    description:
      "Lightweight racerback bra designed for maximum support and breathability.",
    category: "Apparel",
    tags: ["sports bra", "pink", "activewear"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 35,
    variants: {
      colors: ["Pink Quartz"],
      sizes: ["XS", "S", "M", "L"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W9678R_06027_b2_s1_a6_m186_b3e02b79-abfd-4b27-a359-aec54e4bf943_1600x1600.jpg?v=1744848577",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W9678R_06027_b1_s1_a6_m76_2000x2000.jpg?v=1744848577",
    ],
    videoUrl: "",
    rating: {
      average: 4.6,
      count: 24,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "200g",
      material: "Nylon-Spandex blend",
      fit: "Tight fit",
    },
    warranty: "No warranty",
  },
  {
    id: 10,
    productId: "PROD010",
    title: "Alumni Short",
    slug: "alumni-short-pink-quartz",
    brand: "Alo Yoga",
    description: "Comfy and versatile shorts perfect for workouts or lounging.",
    category: "Apparel",
    tags: ["shorts", "pink", "activewear"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 30,
    variants: {
      colors: ["Pink Quartz"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W6273R_06027_b1_s1_a1_m207_1600x1600.jpg?v=1744017652",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W6273R_06027_b1_s1_a2_m207_2000x2000.jpg?v=1744017652",
    ],
    videoUrl: "",
    rating: {
      average: 4.4,
      count: 22,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "15-day return or exchange",
    specifications: {
      weight: "250g",
      material: "Polyester",
      fit: "Relaxed fit",
    },
    warranty: "No warranty",
  },
];

export const TrendingNow = [
  {
    id: 1,
    productId: "PROD001",
    title: "Accolade Crew Neck Pullover",
    slug: "accolade-crew-neck-pullover-seashell-blue",
    brand: "Alo Yoga",
    description:
      "Soft and versatile pullover perfect for casual outings or post-workout comfort.",
    category: "Apparel",
    tags: ["pullover", "crew neck", "blue", "casual", "athleisure"],
    price: 11600,
    discountPrice: 11600,
    currency: "INR",
    inStock: true,
    quantity: 50,
    variants: {
      colors: ["Seashell Blue"],
      sizes: ["S", "M", "L", "XL"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_05442_b1_s1_a1_m233_1600x1600.jpg?v=1749464233",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/U3031RG_05442_b1_s1_a4_m233_2000x2000.jpg?v=1749835805",
    ],
    videoUrl: "",
    rating: {
      average: 4.5,
      count: 32,
    },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "400g",
      material: "Cotton blend",
      fit: "Regular",
    },
    warranty: "No warranty",
  },
];

export const FinishingTouches = [
  {
    id: 1,
    productId: "FT001",
    title: "Alo Runner",
    slug: "alo-runner-white-white",
    brand: "Alo Yoga",
    description:
      "Sleek, comfortable runners perfect for daily wear or workout sessions.",
    category: "Accessories",
    tags: ["runner", "white", "shoes", "sneakers"],
    price: 16700,
    discountPrice: 16700,
    currency: "INR",
    inStock: true,
    quantity: 20,
    variants: {
      colors: ["White/White"],
      sizes: ["6", "7", "8", "9", "10"],
    },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0590U_00000_b1_s1_a1_47d6356e-8d05-4775-800e-0383fe135308_2000x2000.jpg?v=1739918726",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0590U_00000_b1_s1_ai_ea647119-8846-452f-9f5c-12dffd2935f4_2000x2000.png?v=1739988414",
    ],
    videoUrl: "",
    rating: { average: 4.5, count: 42 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "700g",
      material: "Mesh and rubber",
      fit: "Regular",
    },
    warranty: "6 months",
  },
  {
    id: 2,
    productId: "FT002",
    title: "District Trucker Hat",
    slug: "district-trucker-hat-black",
    brand: "Alo Yoga",
    description: "Classic trucker hat with breathable mesh and adjustable fit.",
    category: "Accessories",
    tags: ["hat", "black", "cap"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 50,
    variants: { colors: ["Black"], sizes: null },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0467U_01_b1_a2_2000x2000.jpg?v=1666209001",
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0467U_01_b1_a3_2000x2000.jpg?v=1677708693",
    ],
    videoUrl: "",
    rating: { average: 4.4, count: 33 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "150g",
      material: "Polyester mesh",
      fit: "Adjustable",
    },
    warranty: "No warranty",
  },
  {
    id: 3,
    productId: "FT003",
    title: "Performance Conquer Headband",
    slug: "performance-conquer-headband-black",
    brand: "Alo Yoga",
    description: "Moisture-wicking headband designed for intense workouts.",
    category: "Accessories",
    tags: ["headband", "black", "workout"],
    price: 2900,
    discountPrice: 2900,
    currency: "INR",
    inStock: true,
    quantity: 60,
    variants: { colors: ["Black"], sizes: null },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0518U_01_b1_a1_2000x2000.jpg?v=1745838296",
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0518U_01_b1_a2_2000x2000.jpg?v=1745838296",
    ],
    videoUrl: "",
    rating: { average: 4.3, count: 28 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "50g",
      material: "Elastic blend",
      fit: "Stretch fit",
    },
    warranty: "No warranty",
  },
  {
    id: 4,
    productId: "FT004",
    title: "Unisex Half-Crew Throwback Sock",
    slug: "unisex-half-crew-throwback-sock-white-titanium",
    brand: "Alo Yoga",
    description:
      "Classic half-crew socks with retro style, perfect for casual and sporty looks.",
    category: "Accessories",
    tags: ["socks", "white", "titanium"],
    price: 2900,
    discountPrice: 2900,
    currency: "INR",
    inStock: true,
    quantity: 80,
    variants: { colors: ["White/Titanium"], sizes: ["S", "M", "L"] },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_01_b1_a_2000x2000.jpg?v=1710803229",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_00_b1_a2_m18_2000x2000.jpg?v=1710883061",
    ],
    videoUrl: "",
    rating: { average: 4.6, count: 52 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "100g",
      material: "Cotton blend",
      fit: "Half-crew",
    },
    warranty: "No warranty",
  },
  {
    id: 5,
    productId: "FT005",
    title: "Power Moves Workout Gloves",
    slug: "power-moves-workout-gloves-black",
    brand: "Alo Yoga",
    description:
      "Protect your hands and improve grip during weightlifting or training sessions.",
    category: "Accessories",
    tags: ["gloves", "black", "training"],
    price: 4400,
    discountPrice: 4400,
    currency: "INR",
    inStock: true,
    quantity: 30,
    variants: { colors: ["Black"], sizes: ["S", "M", "L"] },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W7092R_01_1_7a7765fd-6f62-42d6-860f-c74ba7a74fd6_2000x2000.jpg?v=1695420561",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/W7092R_01_1_7a7765fd-6f62-42d6-860f-c74ba7a74fd6_2000x2000.jpg?v=1695420561",
    ],
    videoUrl: "",
    rating: { average: 4.5, count: 37 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "150g",
      material: "Synthetic leather",
      fit: "Snug",
    },
    warranty: "6 months",
  },
  {
    id: 6,
    productId: "FT006",
    title: "Unisex Half-Crew Throwback Sock",
    slug: "unisex-half-crew-throwback-sock-white-seashell-blue",
    brand: "Alo Yoga",
    description: "Sporty socks with retro design in white and seashell blue.",
    category: "Accessories",
    tags: ["socks", "white", "seashell blue"],
    price: 2900,
    discountPrice: 2900,
    currency: "INR",
    inStock: true,
    quantity: 70,
    variants: { colors: ["White/Seashell Blue"], sizes: ["S", "M", "L"] },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_05506_b1_s1_a1_1_2000x2000.jpg?v=1715967967",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_05506_b1_s1_a1_2_2000x2000.jpg?v=1718338573",
    ],
    videoUrl: "",
    rating: { average: 4.5, count: 48 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "100g",
      material: "Cotton blend",
      fit: "Half-crew",
    },
    warranty: "No warranty",
  },
  {
    id: 7,
    productId: "FT007",
    title: "District Trucker Hat",
    slug: "district-trucker-hat-seashell-blue",
    brand: "Alo Yoga",
    description:
      "Light and breathable trucker hat in refreshing seashell blue.",
    category: "Accessories",
    tags: ["hat", "seashell blue", "cap"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 45,
    variants: { colors: ["Seashell Blue"], sizes: null },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0647U_05442_b1_s1_a1_1_2000x2000.jpg?v=1749509291",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0647U_05442_b1_s1_a2_1_2000x2000.jpg?v=1749509291",
    ],
    videoUrl: "",
    rating: { average: 4.4, count: 34 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "150g",
      material: "Polyester mesh",
      fit: "Adjustable",
    },
    warranty: "No warranty",
  },
  {
    id: 8,
    productId: "FT008",
    title: "Performance Off-Duty Cap",
    slug: "performance-off-duty-cap-seashell-blue",
    brand: "Alo Yoga",
    description: "Classic off-duty cap with modern design and adjustable fit.",
    category: "Accessories",
    tags: ["cap", "seashell blue"],
    price: 6200,
    discountPrice: 6200,
    currency: "INR",
    inStock: true,
    quantity: 35,
    variants: { colors: ["Seashell Blue"], sizes: null },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0543U_05442_b1_s1_a2_f9d5b753-f116-4efc-bf99-5a9b56169a33_2000x2000.jpg?v=1750178842",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0543U_05442_b1_s1_a1_de7dd6fd-17ee-424d-93b4-6c6e0f7cb4ff_2000x2000.jpg?v=1750178842",
    ],
    videoUrl: "",
    rating: { average: 4.3, count: 30 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "140g",
      material: "Cotton blend",
      fit: "Adjustable",
    },
    warranty: "No warranty",
  },
  {
    id: 9,
    productId: "FT009",
    title: "Unisex Half-Crew Throwback Sock",
    slug: "unisex-half-crew-throwback-sock-seashell-blue-white",
    brand: "Alo Yoga",
    description: "Retro-inspired half-crew socks in seashell blue and white.",
    category: "Accessories",
    tags: ["socks", "seashell blue", "white"],
    price: 2900,
    discountPrice: 2900,
    currency: "INR",
    inStock: true,
    quantity: 65,
    variants: { colors: ["Seashell Blue/White"], sizes: ["S", "M", "L"] },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_05487_b1_s1_a2_2000x2000.jpg?v=1749763900",
      "https://cdn.shopify.com/s/files/1/2185/2813/files/A0480U_05487_b1_s1_a1_2000x2000.jpg?v=1749763900",
    ],
    videoUrl: "",
    rating: { average: 4.5, count: 50 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "100g",
      material: "Cotton blend",
      fit: "Half-crew",
    },
    warranty: "No warranty",
  },
  {
    id: 10,
    productId: "FT010",
    title: "Unisex Half-Crew Throwback Sock",
    slug: "unisex-half-crew-throwback-sock-white-black",
    brand: "Alo Yoga",
    description:
      "Timeless half-crew socks in classic white and black combination.",
    category: "Accessories",
    tags: ["socks", "white", "black"],
    price: 2900,
    discountPrice: 2900,
    currency: "INR",
    inStock: true,
    quantity: 75,
    variants: { colors: ["White/Black"], sizes: ["S", "M", "L"] },
    images: [
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0480U_0001_b1_a1_2000x2000.jpg?v=1669748933",
      "https://cdn.shopify.com/s/files/1/2185/2813/products/A0480U_0001_b1_a1_m90_2000x2000.jpg?v=1669748933",
    ],
    videoUrl: "",
    rating: { average: 4.5, count: 55 },
    shipping: {
      estimatedDelivery: "5-7 business days",
      shippingFee: 0,
      freeShippingOver: 5000,
    },
    returnPolicy: "30-day return or exchange",
    specifications: {
      weight: "100g",
      material: "Cotton blend",
      fit: "Half-crew",
    },
    warranty: "No warranty",
  },
];

export const ProductReviews = [
  {
    productId: 1,
    reviews: [
      {
        user: "Aarav",
        rating: 5,
        comment: "Excellent quality and very comfortable!",
      },
      {
        user: "Meera",
        rating: 4,
        comment: "Good fit but delivery was slightly late.",
      },
      { user: "Rohit", rating: 5, comment: "Loved the fabric and stitching." },
      { user: "Simran", rating: 4, comment: "Looks stylish, value for money." },
      {
        user: "Kunal",
        rating: 5,
        comment: "Absolutely perfect, highly recommend!",
      },
    ],
  },
  {
    productId: 2,
    reviews: [
      { user: "Priya", rating: 4, comment: "Nice product, feels premium." },
      { user: "Vikram", rating: 3, comment: "Average quality for the price." },
      { user: "Isha", rating: 5, comment: "Exceeded my expectations!" },
      { user: "Arjun", rating: 4, comment: "Good color and comfort." },
      { user: "Riya", rating: 5, comment: "Worth every penny." },
    ],
  },
  {
    productId: 3,
    reviews: [
      { user: "Dev", rating: 5, comment: "Amazing product, love it!" },
      {
        user: "Ananya",
        rating: 4,
        comment: "Looks nice but size runs a bit small.",
      },
      { user: "Karthik", rating: 4, comment: "Comfortable for daily use." },
      { user: "Tanya", rating: 5, comment: "Great material and design." },
      { user: "Sahil", rating: 5, comment: "Would definitely buy again." },
    ],
  },
  {
    productId: 4,
    reviews: [
      { user: "Aditi", rating: 4, comment: "Good quality, nice packaging." },
      { user: "Neeraj", rating: 5, comment: "Loved it, perfect gift!" },
      {
        user: "Shruti",
        rating: 5,
        comment: "Highly satisfied with this purchase.",
      },
      { user: "Kabir", rating: 3, comment: "It’s okay, nothing special." },
      { user: "Pari", rating: 4, comment: "Looks and feels good." },
    ],
  },
  {
    productId: 5,
    reviews: [
      { user: "Rahul", rating: 5, comment: "Top-notch product, very happy!" },
      { user: "Sneha", rating: 4, comment: "Decent for the price." },
      { user: "Manav", rating: 5, comment: "Fantastic quality, super comfy." },
      { user: "Ayesha", rating: 4, comment: "Nice design and build." },
      { user: "Yash", rating: 5, comment: "Exceeded my expectations!" },
    ],
  },
  {
    productId: 6,
    reviews: [
      { user: "Ira", rating: 4, comment: "Comfortable and lightweight." },
      { user: "Raghav", rating: 5, comment: "Perfect fit and finish." },
      { user: "Pooja", rating: 5, comment: "Absolutely love it." },
      {
        user: "Varun",
        rating: 3,
        comment: "Quality is decent but could improve.",
      },
      { user: "Nisha", rating: 4, comment: "Looks premium, feels nice." },
    ],
  },
  {
    productId: 7,
    reviews: [
      { user: "Aditya", rating: 5, comment: "Very happy with the product." },
      { user: "Kavya", rating: 5, comment: "Soft and comfortable fabric." },
      { user: "Rohan", rating: 4, comment: "Good purchase overall." },
      { user: "Diya", rating: 4, comment: "Stylish and durable." },
      { user: "Mihir", rating: 3, comment: "Not bad, but expected better." },
    ],
  },
  {
    productId: 8,
    reviews: [
      { user: "Arnav", rating: 5, comment: "Fantastic, 100% recommended." },
      { user: "Sanya", rating: 4, comment: "Looks good and feels nice." },
      { user: "Om", rating: 5, comment: "Loved the comfort and quality." },
      { user: "Leela", rating: 3, comment: "Okay for casual use." },
      { user: "Jay", rating: 4, comment: "Good quality for the price." },
    ],
  },
  {
    productId: 9,
    reviews: [
      { user: "Aarohi", rating: 4, comment: "Great for daily wear." },
      {
        user: "Siddharth",
        rating: 5,
        comment: "Impressive quality and design.",
      },
      { user: "Nandini", rating: 4, comment: "Nice but slightly expensive." },
      { user: "Harsh", rating: 3, comment: "Average experience." },
      { user: "Trisha", rating: 5, comment: "Exactly what I wanted!" },
    ],
  },
  {
    productId: 10,
    reviews: [
      { user: "Veer", rating: 5, comment: "Perfect in every way." },
      { user: "Anika", rating: 4, comment: "Very good but shipping delayed." },
      { user: "Laksh", rating: 5, comment: "High-quality product." },
      { user: "Ishita", rating: 4, comment: "Looks nice and feels comfy." },
      { user: "Aryan", rating: 5, comment: "Best purchase so far!" },
    ],
  },
];
